### ISSUE TITLE
OS X: Giving up for now :)

### ISSUE THREAD

**Issue by dw** [patrickfrey/strusAnalyzer#11]
Hi Patrick,

Looks like StrusModule wants to depend on strus_private_utils, and I think I can see how to do that, but by starting to cutpaste stuff around which doesn't feel like the right approach.

If you like, I can provide you with SSH access to a 24/7 OS X box. Does that sound useful?

Thanks,

David

**Comment by patrickfrey** [comment]
strus_private_utils is a static library of strus that is not shared with other strus projects. There cannot be any dependency between strusModule and this static library. Some Code is duplicated in strusModule (for example in src/utils.cpp) that can also be found in the strus_private_utils library. I guess that's why you are thinking of a dependency. All shared strus libraries and modules are linked with -fvisibility=hidden. So symbols that are not explicitely exported with DLL_PUBLIC are not visible to other libraries or programs. I guess the problem is that the linker does not find all symbols in strusModule, though they are there. 
But if you give me access, I will have a look. The software was never built on Mac yet. So it's best if I have a look: My email: patrickpfrey (at) yahoo (dot) com

**Comment by patrickfrey** [comment]
We currently try to build Strus on OSx.

**Comment by dw** [comment]
Hi Patrick,

I run an OS X build slave for the PyPy project, it is online 24/7. If you'd like an SSH account on that machine just drop me a private mail (see profile for e-mail address).

In any case I will probably end up playing with this again at the wekend :)

**Comment by dw** [comment]
Whoops, silly, I forgot you included your e-mail address already. Sending you details now.
